apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: monitoring-stack
  namespace: monitoring
spec:
  targetNamespace: monitoring
  createNamespace: true
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  valuesContent: |-
    grafana:
      defaultDashboardsInterval: "5m"
      ingress:
        enabled: true
        path: /monitor
        hosts: [sociedade-civil]
      grafana.ini:
        server:
          domain: sociedade-civil
          root_url: "%(protocol)s://%(domain)s/monitor"
          serve_from_sub_path: true
    prometheus:
      prometheusSpec:
        scrapeInterval: "10s"
        retention: 30d
        retentionSize: 10GB

