---
- name: Converge
  hosts: all
  tasks:
    - name: "Ensure base configuration is done"
      include_role:
        name: "sociedadecivil.cluster_node_base"

    - name: "Install the k3s binary"
      include_role:
        name: "sociedadecivil.base_k3s_setup"

    - name: "Configure and start a k3s server"
      include_role:
        name: "sociedadecivil.base_k3s_setup"