---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: archlinux
    image: docker.sociedadecivil.local/ansible/molecule/archlinux:base
    pre_build_image: true
    dockerfile: instances/archlinux.Dockerfile
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: ansible
