---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  # Check required packages
  - stat:
      path: /usr/local/bin/k3s
    register: k3s_bin

  - name: Assert k3s binary file exists
    assert:
      that: not k3s_bin.stat.exists
      msg: "K3s is installed after playbook runs"
  
  # TODO: Check that k3s is running as a server
