service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
  telemetry:
    resource:
      service.name: jaeger-query
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                # use different port to avoid conflict with collector on 8888
                port: 8887
    logs:
      level: info

extensions:
  healthcheckv2:
    use_v2: true
    http:
      # use different port to avoid conflict with collector on 13133
      endpoint: 0.0.0.0:12133

  jaeger_query:
    storage:
      traces: query_storage
    ui:
      config_file: ./cmd/jaeger/config-ui.json

  jaeger_storage:
    backends:
      query_storage:
        memory:
          max_traces: 100000
      exporter_storage:
        memory:
          max_traces: 100000

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: exporter_storage