---
- name: Converge
  hosts: all
  tasks:
    - name: "Ensure base configuration is done"
      include_role:
        name: "sociedadecivil.cluster_node_base"

    - name: "Include sociedadecivil.base_k3s_setup"
      include_role:
        name: "sociedadecivil.base_k3s_setup"
