---
- name: Install sudo
  community.general.pacman:
    name: sudo
    state: present

- name: Install docker
  community.general.pacman:
    name: docker
    state: present

- name: Ensure docker service is running and enabled
  systemd:
    name: docker
    state: started
    enabled: yes
